[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100


[tool.pytest]
testpaths = ["tests"]
addopts = ["--cov=my_package", "--cov-report=html", "--cov-report=term"]
